### ISSUE TITLE
Feature Request: nsfw tag for generate image command

### ISSUE THREAD

**Issue by kmatthews123** [joshbuker/discord-bot#2]
Requesting feature to add an additional option for image generate command to allow for preemptive tagging of images as being NSFW. this would likely involve including the spoiler tag to the response message if the option is called. It doesn't seem like discord will let a mod edit a users message to add that tag and will only allow for a mod to delete the image. 

Alternatively it could be implemented by injecting a NSFW negative prompt by default to the generate images command and add an option to allow nsfw images by turning off the negative prompt injection on an image by image basis. this would likely be a more solid implementation but I don't know if it will be more difficult or if there are other reasons why this would be undesirable.

**Comment by joshbuker** [comment]
There's three components to this:
- Flagging the prompts used
- Flagging the image generated
- Manually flagging preemptively

Two are already implemented, flagging the image generated (not totally reliable, but better than nothing), and manual flagging (basically, do you suspect this might have issues because of vector adjacency).

Flagging based on the prompt/model used is yet to be implemented.
